# Generated by Django 5.2.4 on 2025-12-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('brand', models.CharField(blank=True, help_text='Brand or source (optional).', max_length=100)),
                ('category', models.CharField(blank=True, help_text="Category like 'protein', 'carb', 'fat', 'recipe', 'snack', etc.", max_length=100)),
                ('is_recipe', models.BooleanField(default=False, help_text='Check if this is a multi-ingredient recipe rather than a single ingredient.')),
                ('calories_per_serving', models.PositiveIntegerField(help_text='Calories per serving.')),
                ('protein_g_per_serving', models.DecimalField(decimal_places=1, help_text='Protein (g) per serving.', max_digits=6)),
                ('carbs_g_per_serving', models.DecimalField(decimal_places=1, help_text='Carbohydrates (g) per serving.', max_digits=6)),
                ('fats_g_per_serving', models.DecimalField(decimal_places=1, help_text='Fat (g) per serving.', max_digits=6)),
                ('fiber_g_per_serving', models.DecimalField(decimal_places=1, default=0, help_text='Fiber (g) per serving.', max_digits=6)),
                ('serving_name', models.CharField(blank=True, help_text='e.g. "1 slice", "1 cup", "1 cookie" (optional).', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Any notes about this food (e.g. special handling, recipe details).')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this food from future planning while keeping history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
