# Generated by Django 5.2.4 on 2025-12-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='calories_per_serving',
        ),
        migrations.RemoveField(
            model_name='food',
            name='fiber_g_per_serving',
        ),
    ]
