# Generated by Django 5.2.4 on 2025-12-16 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMacroLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('required_calories', models.PositiveIntegerField(blank=True, help_text='Target total calories for this specific day.', null=True)),
                ('required_protein_grams', models.DecimalField(blank=True, decimal_places=1, help_text='Target grams of protein for this day.', max_digits=6, null=True)),
                ('required_carbs_grams', models.DecimalField(blank=True, decimal_places=1, help_text='Target grams of carbohydrates for this day.', max_digits=6, null=True)),
                ('required_fats_grams', models.DecimalField(blank=True, decimal_places=1, help_text='Target grams of fat for this day.', max_digits=6, null=True)),
                ('required_fiber_grams', models.DecimalField(blank=True, decimal_places=1, help_text='Target grams of fiber for this day.', max_digits=6, null=True)),
                ('actual_calories', models.PositiveIntegerField(blank=True, help_text='Sum of calories from all meals/portions for this day.', null=True)),
                ('actual_protein_grams', models.DecimalField(blank=True, decimal_places=1, help_text='Total grams of protein actually planned for this day.', max_digits=6, null=True)),
                ('actual_carbs_grams', models.DecimalField(blank=True, decimal_places=1, help_text='Total grams of carbohydrates actually planned for this day.', max_digits=6, null=True)),
                ('actual_fats_grams', models.DecimalField(blank=True, decimal_places=1, help_text='Total grams of fat actually planned for this day.', max_digits=6, null=True)),
                ('actual_fiber_grams', models.DecimalField(blank=True, decimal_places=1, help_text='Total grams of fiber actually planned for this day.', max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any notes about this day (training day, sick, special event, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'person__name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this person (preferences, restrictions, etc.).')),
                ('daily_calories', models.PositiveIntegerField(blank=True, help_text='Target total calories per day.', null=True)),
                ('protein_grams', models.DecimalField(blank=True, decimal_places=1, help_text='Target grams of protein per day.', max_digits=6, null=True)),
                ('carbs_grams', models.DecimalField(blank=True, decimal_places=1, help_text='Target grams of carbohydrates per day.', max_digits=6, null=True)),
                ('fats_grams', models.DecimalField(blank=True, decimal_places=1, help_text='Target grams of fat per day.', max_digits=6, null=True)),
                ('fiber_grams', models.DecimalField(blank=True, decimal_places=1, help_text='Target grams of fiber per day (optional).', max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck if this person is no longer being tracked.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Breakfast", "Lunch", or a custom name like "Post-workout".', max_length=100)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('other', 'Other')], default='other', max_length=20)),
                ('order', models.PositiveIntegerField(default=1, help_text='Controls display order of meals within the day (1 = first).')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this specific meal.')),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='accounts.dailymacrolog')),
            ],
            options={
                'ordering': ['daily_log__date', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.DecimalField(decimal_places=2, help_text='How many servings of this food in the meal (e.g. 1.5).', max_digits=6)),
                ('calories', models.PositiveIntegerField(blank=True, help_text='Total calories from this item in the meal (optional cache).', null=True)),
                ('protein_grams', models.DecimalField(blank=True, decimal_places=2, help_text='Total grams of protein from this item (optional cache).', max_digits=7, null=True)),
                ('carbs_grams', models.DecimalField(blank=True, decimal_places=2, help_text='Total grams of carbohydrates from this item (optional cache).', max_digits=7, null=True)),
                ('fats_grams', models.DecimalField(blank=True, decimal_places=2, help_text='Total grams of fat from this item (optional cache).', max_digits=7, null=True)),
                ('fiber_grams', models.DecimalField(blank=True, decimal_places=2, help_text='Total grams of fiber from this item (optional cache).', max_digits=7, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for this specific item (e.g. adjustments, brand detail).')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_items', to='foods.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.meal')),
            ],
            options={
                'ordering': ['meal__order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='dailymacrolog',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='accounts.person'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymacrolog',
            unique_together={('person', 'date')},
        ),
    ]
