# Generated by Django 5.2.4 on 2025-12-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymacrolog',
            name='actual_calories',
        ),
        migrations.RemoveField(
            model_name='dailymacrolog',
            name='actual_fiber_grams',
        ),
        migrations.RemoveField(
            model_name='dailymacrolog',
            name='required_calories',
        ),
        migrations.RemoveField(
            model_name='dailymacrolog',
            name='required_fiber_grams',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='fiber_grams',
        ),
        migrations.RemoveField(
            model_name='person',
            name='daily_calories',
        ),
        migrations.RemoveField(
            model_name='person',
            name='fiber_grams',
        ),
    ]
