# Generated by Django 5.2.4 on 2025-12-18 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_dailymacrolog_actual_calories_and_more'),
        ('foods', '0002_remove_food_calories_per_serving_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealitem',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='food',
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('other', 'Other')], default='other', max_length=20)),
                ('servings', models.DecimalField(decimal_places=2, help_text='How many servings of this food (e.g. 1.5).', max_digits=6)),
                ('protein_grams', models.DecimalField(blank=True, decimal_places=2, help_text='Total grams of protein from this entry (optional cache).', max_digits=7, null=True)),
                ('carbs_grams', models.DecimalField(blank=True, decimal_places=2, help_text='Total grams of carbohydrates from this entry (optional cache).', max_digits=7, null=True)),
                ('fats_grams', models.DecimalField(blank=True, decimal_places=2, help_text='Total grams of fat from this entry (optional cache).', max_digits=7, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for this entry (e.g. adjustments, brand detail).')),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to='accounts.dailymacrolog')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_entries', to='foods.food')),
            ],
            options={
                'ordering': ['daily_log__date', 'meal_type', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='MealItem',
        ),
    ]
